spring.application.name=donation-service
server.port=${PORT:${SERVER_PORT:8083}}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/microlift_donation_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

# Razorpay Test Credentials (REPLACE WITH YOUR KEYS)
razorpay.key_id=rzp_test_YourKeyHere
razorpay.key_secret=YourSecretHere

